version: "3"

services:  
  qiam:    
    image: qriarlabs/qiam:latest        
    command: 
      - start-dev
      - --spi-theme-default=qiam
      - --spi-theme-welcome-theme=qiam
      - --spi-theme-login-theme=qiam
      - --spi-theme-account-theme=qiam
      - --spi-theme-admin-theme=qiam
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: db_name
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: user_name
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin      
    ports:      
      - "8080:8080"      
    depends_on:      
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/providers:/opt/keycloak/providers
      - ${PWD}/themes:/opt/keycloak/themes
    networks:
      network_sso:
        ipv4_address: "10.0.0.2"    

  postgres: 
    image: postgres:14.9
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'    
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "35432:5432"
    networks:
      network_sso:
        ipv4_address: "10.0.0.3"
networks:  
  network_sso:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"    
