version: "3.3"
services:

  qiam:

    #image: quay.io/keycloak/keycloak:latest
    # image: qriarlabs/qiam:${QIAM_VERSION_TAG}
    #image: quay.io/keycloak/keycloak:22.0.3
    #image: qriarlabs/qiam:${QIAM_VERSION_TAG}
    restart: always
    entrypoint: "/opt/keycloak/bin/kc.sh start --hostname-strict=false --http-enabled=true --proxy edge --spi-theme-default=qiam --spi-theme-welcome-theme=qiam --spi-theme-login-theme=qiam --spi-theme-account-theme=qiam --spi-theme-admin-theme=qiam --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
    #entrypoint: "/opt/keycloak/bin/kc.sh start --hostname-strict=false --http-enabled=true --proxy edge"
    env_file:
      - .env
    volumes:
      - ${PWD}/extensions/authenticators/passwordless-magiclink/target/qriarlabs.magiclink-passwordless.jar:/opt/keycloak/providers/qriarlabs.magiclink-passwordless.jar
      - ${PWD}/extensions/authenticators/kc-api-sms-otp/target/qriarlabs.api-based-keycloak-2fa-sms-authenticator.jar:/opt/keycloak/providers/qriarlabs.api-based-keycloak-2fa-sms-authenticator.jar
      - ${PWD}/themes:/opt/keycloak/themes
    networks:
      - qiam-network
    environment:      
      - KEYCLOAK_LOGLEVEL=ALL
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HTTP_ENABLED=true
      - KEYCLOAK_ADMIN=$QIAM_ADMIN_USERNAME
      - KEYCLOAK_PASSWORD=$QIAM_ADMIN_PASSWORD
      - KC_DB_USERNAME=$QIAM_DATABASE_USERNAME
      - KC_DB_PASSWORD=$QIAM_DATABASE_PASSWORD
      - KC_DB=$QIAM_DATABASE
      - KC_DB_URL_HOST=$QIAM_DATABASE_HOST
      - KC_DB_URL_DATABASE=$QIAM_DATABASE_NAME
      - KC_DB_URL_PORT=$QIAM_DATABASE_PORT 
      - KC_DB_SCHEMA=$QIAM_DATABASE_SCHEMA
      - KEYCLOAK_PRODUCTION=true
      - KEYCLOAK_PROXY=edge
      - KEYCLOAK_EXTRA_ARGS=--auto-build
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0
    ports:      
      - "8080:8080"      
    depends_on:      
      postgres:
        condition: service_healthy

  postgres: 
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$QIAM_DATABASE_USERNAME", "-d", "$QIAM_DATABASE_NAME", "-h", "$QIAM_DATABASE_HOST", "-p", "$QIAM_DATABASE_PORT"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_USER=$QIAM_DATABASE_USERNAME
      - POSTGRES_PASSWORD=$QIAM_DATABASE_PASSWORD
      - POSTGRES_DB=$QIAM_DATABASE_NAME
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - qiam-network

networks:  
  qiam-network:
    driver: bridge
