name: Deploy Docusaurus

on:
  push:
    branches:
      - main  # Ou sua branch de trabalho

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
      working-directory: docs  # Change this to the directory of your Docusaurus project

    - name: Build website
      run: npm run build
      working-directory: docs  # Ensure this is the directory where your Docusaurus config is located

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build  # Update this path if your build directory is different
